### ISSUE TITLE
Scoped component causes react error if it has no children

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/kremling#17]
If you render `<Scoped css="& .foo {}" />` (with no children), you get the following error in the console:

![screenshot from 2018-10-08 10-19-38](https://user-images.githubusercontent.com/5524384/46621120-daada480-cae3-11e8-9971-c3340a90588d.png)

**Comment by blittle** [comment]
Just don't do that 🤣

**Comment by joeldenning** [comment]
@MikeBordelon is going to work on this one
