### ISSUE TITLE
Make Scoped component 'css' prop handle kremling-loader (postcss) object

### ISSUE THREAD

**Issue by geoctrl** [CanopyTax/kremling#35]
Currently, the `useCss` hook handles both strings (regular css) and objects (`kremling-loader` css).

I'm thinking it would be great to move in that direction for the `<Scoped>` `css` prop as well, and eventually deprecate the `postcss` prop.

Deprecating the `postcss` prop would be a breaking change, but it would be pretty easy to fix in any-sized project:

find/replace: `postcss=` => `css=`

**Comment by joeldenning** [comment]
👍 i like it
