### ISSUE TITLE
TypeScript: Module has no exported member 'Scoped'.

### ISSUE THREAD

**Issue by sand-head** [CanopyTax/kremling#40]
Trying to use this library and its loader in a TypeScript project. My root component is a class component, so as per the Kremling docs, I'm attempting to import and use the `<Scoped>` tag. However, it seems like it isn't defined in Kremling's definitions file, so TypeScript is unable to confirm it exists.

**Comment by joeldenning** [comment]
I confirmed that Scoped does not exist in https://github.com/CanopyTax/kremling/blob/master/src/kremling.d.ts. Would you be willing to create a pull request to fix this?

**Comment by sand-head** [comment]
Yeah, sure thing.

**Comment by joeldenning** [comment]
Resolved in #41 and published in https://github.com/CanopyTax/kremling/releases/tag/v2.0.2
