### ISSUE TITLE
move kremling into a new @kremlingjs org

### ISSUE THREAD

**Issue by geoctrl** [CanopyTax/kremling#64]
I'm thinking about moving kremling into it's own org, which would give us a single place to manage all of kremling's ecosystem:

- core kremling
- kremling-babel-plugin
- kremling-loader
- postcss-kremling-plugin
- kremling vscode plugin for syntax highlighting

`@kremlingjs` org name is available 🤷‍♀️

**Comment by geoctrl** [comment]
this could also be a good opportunity to convert the core kremling library into a mono repo so we can add support for other libraries besides react

**Comment by joeldenning** [comment]
I'm supportive of this.

**Comment by geoctrl** [comment]
created new org: https://github.com/kremlingjs

kremling mono repo: https://github.com/kremlingjs/kremling

currently have the `Scoped` component working in react & preact

going to move all new github issues to that repo moving forward
